# Generated by Django 2.1 on 2018-09-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Imuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imuser.User')),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['user'],
            },
        ),
    ]
