# Generated by Django 2.1 on 2018-09-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户名'),
        ),
    ]
